export enum ErrorCode {
  USER_NOT_INITIALIZED = 'USER_NOT_INITIALIZED',
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
}
