export enum ErrorCode {
  USER_NOT_INITIALIZED = 'USER_NOT_INITIALIZED',
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
  JOIN_REQUEST_ALREADY_EXISTS = 'JOIN_REQUEST_ALREADY_EXISTS',
  APARTMENT_ALREADY_LINKED = 'APARTMENT_ALREADY_LINKED',
  HOUSE_REJOIN_UNAVAILABLE = 'HOUSE_REJOIN_UNAVAILABLE',
}
